CREATE PROCEDURE AjouterCOMMANDE
 @ID int OUTPUT,
 @ID_CLIENT int,
 @DATE date,
 @DATE_DE_PAIMENT date
AS
 INSERT INTO COMMANDE(ID_CLIENT,DATE,DATE_DE_PAIMENT)
  VALUES(@ID_CLIENT,@DATE,@DATE_DE_PAIMENT)
 SET @ID=@@IDENTITY
RETURN
GO
CREATE PROCEDURE ModifierCOMMANDE
 @ID int,
 @ID_CLIENT int,
 @DATE date,
 @DATE_DE_PAIMENT date
AS
 IF(@ID IS NULL OR @ID=0)
  RAISERROR('Identifiant requis !',16,1)
 ELSE  UPDATE COMMANDE
        SET ID_CLIENT=@ID_CLIENT,DATE=@DATE,DATE_DE_PAIMENT=@DATE_DE_PAIMENT
        WHERE ID=@ID
RETURN
GO
CREATE PROCEDURE SelectionnerCOMMANDE
 @Index VARCHAR(10)
AS
 IF(@Index='ID_CLIENT') SELECT * FROM COMMANDE ORDER BY ID_CLIENT
 ELSE IF(@Index='DATE') SELECT * FROM COMMANDE ORDER BY DATE
 ELSE IF(@Index='DATE_DE_PAIMENT') SELECT * FROM COMMANDE ORDER BY DATE_DE_PAIMENT
 ELSE SELECT * FROM COMMANDE ORDER BY ID
RETURN
GO
CREATE PROCEDURE SelectionnerCOMMANDE_ID
 @ID int
AS
 IF(@ID IS NULL)
  RAISERROR('Identifiant requis !',16,1)
 ELSE
  SELECT ID,ID_CLIENT,DATE,DATE_DE_PAIMENT
  FROM COMMANDE
  WHERE @ID=ID
RETURN
GO
CREATE PROCEDURE SupprimerCOMMANDE
 @ID int
AS
 IF(@ID IS NULL)
  RAISERROR('Identifiant requis !',16,1)
 ELSE
  DELETE FROM COMMANDE WHERE @ID=ID
RETURN
GO
