CREATE PROCEDURE AjouterDETAIL_COMMANDE
 @ID int OUTPUT,
 @ID_COMMANDE int,
 @ID_MEUBLES int
AS
 INSERT INTO DETAIL_COMMANDE(ID_COMMANDE,ID_MEUBLES)
  VALUES(@ID_COMMANDE,@ID_MEUBLES)
 SET @ID=@@IDENTITY
RETURN
GO
CREATE PROCEDURE ModifierDETAIL_COMMANDE
 @ID int,
 @ID_COMMANDE int,
 @ID_MEUBLES int
AS
 IF(@ID IS NULL OR @ID=0)
  RAISERROR('Identifiant requis !',16,1)
 ELSE  UPDATE DETAIL_COMMANDE
        SET ID_COMMANDE=@ID_COMMANDE,ID_MEUBLES=@ID_MEUBLES
        WHERE ID=@ID
RETURN
GO
CREATE PROCEDURE SelectionnerDETAIL_COMMANDE
 @Index VARCHAR(10)
AS
 IF(@Index='ID_COMMANDE') SELECT * FROM DETAIL_COMMANDE ORDER BY ID_COMMANDE
 ELSE IF(@Index='ID_MEUBLES') SELECT * FROM DETAIL_COMMANDE ORDER BY ID_MEUBLES
 ELSE SELECT * FROM DETAIL_COMMANDE ORDER BY ID
RETURN
GO
CREATE PROCEDURE SelectionnerDETAIL_COMMANDE_ID
 @ID int
AS
 IF(@ID IS NULL)
  RAISERROR('Identifiant requis !',16,1)
 ELSE
  SELECT ID,ID_COMMANDE,ID_MEUBLES
  FROM DETAIL_COMMANDE
  WHERE @ID=ID
RETURN
GO
CREATE PROCEDURE SupprimerDETAIL_COMMANDE
 @ID int
AS
 IF(@ID IS NULL)
  RAISERROR('Identifiant requis !',16,1)
 ELSE
  DELETE FROM DETAIL_COMMANDE WHERE @ID=ID
RETURN
GO
