CREATE PROCEDURE AjouterMEUBLE
 @ID int OUTPUT,
 @NOM varchar(50),
 @PRIX_UNITAIRE float,
 @TEMPS_DE_FABRICATION varchar(50)
AS
 INSERT INTO MEUBLE(NOM,PRIX_UNITAIRE,TEMPS_DE_FABRICATION)
  VALUES(@NOM,@PRIX_UNITAIRE,@TEMPS_DE_FABRICATION)
 SET @ID=@@IDENTITY
RETURN
GO
CREATE PROCEDURE ModifierMEUBLE
 @ID int,
 @NOM varchar(50),
 @PRIX_UNITAIRE float,
 @TEMPS_DE_FABRICATION varchar(50)
AS
 IF(@ID IS NULL OR @ID=0)
  RAISERROR('Identifiant requis !',16,1)
 ELSE  UPDATE MEUBLE
        SET NOM=@NOM,PRIX_UNITAIRE=@PRIX_UNITAIRE,TEMPS_DE_FABRICATION=@TEMPS_DE_FABRICATION
        WHERE ID=@ID
RETURN
GO
CREATE PROCEDURE SelectionnerMEUBLE
 @Index VARCHAR(10)
AS
 IF(@Index='NOM') SELECT * FROM MEUBLE ORDER BY NOM
 ELSE IF(@Index='PRIX_UNITAIRE') SELECT * FROM MEUBLE ORDER BY PRIX_UNITAIRE
 ELSE IF(@Index='TEMPS_DE_FABRICATION') SELECT * FROM MEUBLE ORDER BY TEMPS_DE_FABRICATION
 ELSE SELECT * FROM MEUBLE ORDER BY ID
RETURN
GO
CREATE PROCEDURE SelectionnerMEUBLE_ID
 @ID int
AS
 IF(@ID IS NULL)
  RAISERROR('Identifiant requis !',16,1)
 ELSE
  SELECT ID,NOM,PRIX_UNITAIRE,TEMPS_DE_FABRICATION
  FROM MEUBLE
  WHERE @ID=ID
RETURN
GO
CREATE PROCEDURE SupprimerMEUBLE
 @ID int
AS
 IF(@ID IS NULL)
  RAISERROR('Identifiant requis !',16,1)
 ELSE
  DELETE FROM MEUBLE WHERE @ID=ID
RETURN
GO
