CREATE PROCEDURE AjouterSTOCK
 @ID int OUTPUT,
 @ID_MEUBLE int,
 @QUANTITE int,
 @ETAT_DE_FABRICATION varchar(50),
 @DELAI_DE_LIVRAISON int
AS
 INSERT INTO STOCK(ID_MEUBLE,QUANTITE,ETAT_DE_FABRICATION,DELAI_DE_LIVRAISON)
  VALUES(@ID_MEUBLE,@QUANTITE,@ETAT_DE_FABRICATION,@DELAI_DE_LIVRAISON)
 SET @ID=@@IDENTITY
RETURN
GO
CREATE PROCEDURE ModifierSTOCK
 @ID int,
 @ID_MEUBLE int,
 @QUANTITE int,
 @ETAT_DE_FABRICATION varchar(50),
 @DELAI_DE_LIVRAISON int
AS
 IF(@ID IS NULL OR @ID=0)
  RAISERROR('Identifiant requis !',16,1)
 ELSE  UPDATE STOCK
        SET ID_MEUBLE=@ID_MEUBLE,QUANTITE=@QUANTITE,ETAT_DE_FABRICATION=@ETAT_DE_FABRICATION,DELAI_DE_LIVRAISON=@DELAI_DE_LIVRAISON
        WHERE ID=@ID
RETURN
GO
CREATE PROCEDURE SelectionnerSTOCK
 @Index VARCHAR(10)
AS
 IF(@Index='ID_MEUBLE') SELECT * FROM STOCK ORDER BY ID_MEUBLE
 ELSE IF(@Index='QUANTITE') SELECT * FROM STOCK ORDER BY QUANTITE
 ELSE IF(@Index='ETAT_DE_FABRICATION') SELECT * FROM STOCK ORDER BY ETAT_DE_FABRICATION
 ELSE IF(@Index='DELAI_DE_LIVRAISON') SELECT * FROM STOCK ORDER BY DELAI_DE_LIVRAISON
 ELSE SELECT * FROM STOCK ORDER BY ID
RETURN
GO
CREATE PROCEDURE SelectionnerSTOCK_ID
 @ID int
AS
 IF(@ID IS NULL)
  RAISERROR('Identifiant requis !',16,1)
 ELSE
  SELECT ID,ID_MEUBLE,QUANTITE,ETAT_DE_FABRICATION,DELAI_DE_LIVRAISON
  FROM STOCK
  WHERE @ID=ID
RETURN
GO
CREATE PROCEDURE SupprimerSTOCK
 @ID int
AS
 IF(@ID IS NULL)
  RAISERROR('Identifiant requis !',16,1)
 ELSE
  DELETE FROM STOCK WHERE @ID=ID
RETURN
GO
